### ISSUE TITLE
win32gui not install

### ISSUE THREAD

**Issue by gabrielmarkusmt** [SumZer0-git/EDAPGui#34]
Collecting win32gui
  Using cached win32gui-221.5.tar.gz (605 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Teixeira\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Teixeira\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Teixeira\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Teixeira\AppData\Local\Temp\pip-build-env-6r3ned9e\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Teixeira\AppData\Local\Temp\pip-build-env-6r3ned9e\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\Teixeira\AppData\Local\Temp\pip-build-env-6r3ned9e\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Teixeira\AppData\Local\Temp\pip-build-env-6r3ned9e\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "C:\Users\Teixeira\AppData\Local\Temp\pip-install-6l1eu34y\win32gui_5d860a9060254a288f917c837d39f25a\win32\distutils\gui.py", line 6, in <module>
          from .command import win32_build_ext
      ModuleNotFoundError: No module named 'win32.distutils.command'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by SumZer0-git** [comment]
from another person that was having problems with installing win32gui:

"..however...pywin32 includes the necessary files so simply removing win32gui from your requirements file fixes that issue."

so remove that line from the requirements.txt file
